### PR TITLE
Add new Data Exporer content

### PR DESCRIPTION
**Pull request by jthomasmock**
Add the new images and text for latest features in Data Explorer.

### CODE REVIEW

**Comment by juliasilge** [comment]
@jthomasmock can you take a look at the sizing of those images and set them to be a bit more pleasant.

For example, this change:

Screenshot 2024-11-20 at 10 35 23 AM

results in this:

Screenshot 2024-11-20 at 10 35 46 AM

**Comment by jthomasmock** [comment]
> @jthomasmock can you take a look at the sizing of those images and set them to be a bit more pleasant.
> 
> For example, this change:
> 
> Screenshot 2024-11-20 at 10 35 23 AM
> 
> results in this:
> 
> Screenshot 2024-11-20 at 10 35 46 AM

Made some changes, thanks!

**Comment by juliasilge** [comment]
@jthomasmock The rest of the site uses centered images. Is it OK if I switch these back to centered?

**Comment by jthomasmock** [comment]
> @jthomasmock The rest of the site uses centered images. Is it OK if I switch these back to centered?

Of course, sorry for the churn. I've gone ahead w/ those changes.

**Review by juliasilge — APPROVED** [review]
Thank you!

**Pull request merged**
